import * as React from 'react';
import Head from 'next/head';

const About = () => {
  return (
    <div>
      <Head>
        <title>About Ensar Bavrk</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>This will be about page here</h1>
      </main>
    </div>
  );
};

export default About;
