import Head from 'next/head';
import { BlogPageHeading } from '@/molecules/BlogPageHeading';
import { BlogSummaryCard } from '@/organisms/BlogSummaryCard';
import { getAllPosts } from '@/lib/postsApi';
import styles from './index.module.scss';
import { H2, P, Small } from '@/atoms/Typography';
export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>Enso&apos;s digital garden</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-row my-20">
        <div className={styles.heroImage}>
          <img
            className={styles.static}
            src="/images/assets/static.png"
            alt={'hero image of enso'}
          />
          <img
            className={styles.gif}
            src="/images/assets/enso.gif"
            alt={'hero image of enso gif'}
          />
        </div>
        <div className="flex flex-col ml-9">
          <H2 className="mb-6">
            Hi, I'm <span className={'text-primary'}>Enso.</span>
          </H2>
          <P className="mb-3">
            I build things and enjoy programming, designing, console logging,
            and all things outside!{' '}
            <span className="block mt-4">Currently making the @UVA app!</span>
          </P>
        </div>
      </div>

      <div className="mt-9">
        <BlogPageHeading />
        <ul className={'mb-9'}>
          {posts.map((post) => {
            return <BlogSummaryCard key={post.meta.title} meta={post.meta} />;
          })}
        </ul>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const posts = getAllPosts();
  return {
    props: {
      posts,
    },
  };
}
