import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Enso&apos;s digital garden</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>This will be my digital garden.</h1>
      </main>
    </div>
  );
}
