import Head from 'next/head';
import { BlogPageHeading } from '@/molecules/BlogPageHeading';
import { BlogSummaryCard } from '@/organisms/BlogSummaryCard';
import {getAllPosts} from "@/lib/postsApi";

export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>Enso&apos;s digital garden</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mt-9">
        <BlogPageHeading />
        <ul className={'mb-9'}>
          {posts.map((post) => {
            return <BlogSummaryCard key={post.meta.title} meta={post.meta} />;
          })}
        </ul>
      </div>
    </div>
  );
}

export async function getStaticProps() {
    const posts = getAllPosts();
    return {
        props: {
            posts,
        },
    };
}
